#!/usr/bin/env node

/**
 * Build script to inject environment variables into firebase-config.js
 * Run this before deploying: node build-config.js
 * Or add to package.json scripts
 */

const fs = require('fs');
const path = require('path');

// Read environment variables
const envVars = {
    apiKey: process.env.VITE_FIREBASE_API_KEY || '',
    authDomain: process.env.VITE_FIREBASE_AUTH_DOMAIN || '',
    projectId: process.env.VITE_FIREBASE_PROJECT_ID || '',
    storageBucket: process.env.VITE_FIREBASE_STORAGE_BUCKET || '',
    messagingSenderId: process.env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
    appId: process.env.VITE_FIREBASE_APP_ID || '',
    measurementId: process.env.VITE_FIREBASE_MEASUREMENT_ID || ''
};

// Default values (fallback)
const defaults = {
    apiKey: "AIzaSyApT0uj8sz3mC8bDtLQeHHodAtZlqfJDns",
    authDomain: "rajjecampaign.firebaseapp.com",
    projectId: "rajjecampaign",
    storageBucket: "rajjecampaign.firebasestorage.app",
    messagingSenderId: "480799282234",
    appId: "1:480799282234:web:a35c084610bcdfc2ed9103",
    measurementId: "G-2K7J967N1V"
};

// Generate config file
const configContent = `// Firebase Configuration
// Auto-generated from environment variables
// DO NOT EDIT THIS FILE MANUALLY - it will be overwritten

const firebaseConfig = {
    apiKey: ${JSON.stringify(envVars.apiKey || defaults.apiKey)},
    authDomain: ${JSON.stringify(envVars.authDomain || defaults.authDomain)},
    projectId: ${JSON.stringify(envVars.projectId || defaults.projectId)},
    storageBucket: ${JSON.stringify(envVars.storageBucket || defaults.storageBucket)},
    messagingSenderId: ${JSON.stringify(envVars.messagingSenderId || defaults.messagingSenderId)},
    appId: ${JSON.stringify(envVars.appId || defaults.appId)},
    measurementId: ${JSON.stringify(envVars.measurementId || defaults.measurementId)}
};

export { firebaseConfig };
`;

// Write to file
const configPath = path.join(__dirname, 'firebase-config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✅ Firebase config generated successfully');
if (Object.values(envVars).some(v => v)) {
    console.log('📝 Using environment variables');
} else {
    console.log('⚠️  Using default values (no environment variables found)');
}