// Firebase Configuration
// This file is auto-generated by build-config.js from environment variables
// Default values below (will be replaced during build if env vars are set)
// DO NOT EDIT THIS FILE MANUALLY - run "node build-config.js" to regenerate

const firebaseConfig = {
    apiKey: "AIzaSyApT0uj8sz3mC8bDtLQeHHodAtZlqfJDns",
    authDomain: "rajjecampaign.firebaseapp.com",
    projectId: "rajjecampaign",
    storageBucket: "rajjecampaign.firebasestorage.app",
    messagingSenderId: "480799282234",
    appId: "1:480799282234:web:a35c084610bcdfc2ed9103",
    measurementId: "G-2K7J967N1V"
};

export {
    firebaseConfig
};